-- MySQL Script generated by MySQL Workbench
-- Mon Oct 28 12:44:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`class_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`class_info` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`class_info` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `department` VARCHAR(300) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `subject` VARCHAR(400) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `course number` VARCHAR(200) NULL DEFAULT NULL,
  `course name` VARCHAR(6000) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4917;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`department_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`department_info` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`department_info` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(3000) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `abv` VARCHAR(300) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 100;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`instructor_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructor_info` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`instructor_info` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(3000) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `gender` VARCHAR(20) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `department` VARCHAR(400) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7820;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`instructors_teach_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructors_teach_classes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`instructors_teach_classes` (
  `instructor_info_id` INT(11) UNSIGNED NOT NULL,
  `class_info_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`instructor_info_id`, `class_info_id`),
  CONSTRAINT `fk_instructor_info_has_class_info_instructor_info2`
    FOREIGN KEY (`instructor_info_id`)
    REFERENCES `mydb`.`instructor_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instructor_info_has_class_info_class_info2`
    FOREIGN KEY (`class_info_id`)
    REFERENCES `mydb`.`class_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_instructor_info_has_class_info_class_info2_idx` ON `mydb`.`instructors_teach_classes` (`class_info_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_instructor_info_has_class_info_instructor_info2_idx` ON `mydb`.`instructors_teach_classes` (`instructor_info_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`grade_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`grade_info` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`grade_info` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `semester` VARCHAR(40) NULL DEFAULT NULL,
  `department` VARCHAR(30) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `subject` VARCHAR(30) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `course number` INT(11) NULL DEFAULT NULL,
  `instructor name` VARCHAR(4000) COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `number of students` INT(11) NULL DEFAULT NULL,
  `avg GPA` FLOAT NULL DEFAULT NULL,
  `A%` FLOAT NULL DEFAULT NULL,
  `B%` FLOAT NULL DEFAULT NULL,
  `C%` FLOAT NULL DEFAULT NULL,
  `D%` FLOAT NULL DEFAULT NULL,
  `A+` INT(11) NULL DEFAULT NULL,
  `A` INT(11) NULL DEFAULT NULL,
  `A-` INT(11) NULL DEFAULT NULL,
  `B+` INT(11) NULL DEFAULT NULL,
  `B` INT(11) NULL DEFAULT NULL,
  `B-` INT(11) NULL DEFAULT NULL,
  `C+` INT(11) NULL DEFAULT NULL,
  `C` INT(11) NULL DEFAULT NULL,
  `C-` INT(11) NULL DEFAULT NULL,
  `D+` INT(11) NULL DEFAULT NULL,
  `D` INT(11) NULL DEFAULT NULL,
  `D-` INT(11) NULL DEFAULT NULL,
  `F` INT(11) NULL DEFAULT NULL,
  `W` INT(11) NULL DEFAULT NULL,
  `I` INT(11) NULL DEFAULT NULL,
  `other grade` INT(11) NULL DEFAULT NULL,
  `instructors_teach_classes_instructor_info_id` INT(11) UNSIGNED NOT NULL,
  `instructors_teach_classes_class_info_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `instructors_teach_classes_instructor_info_id`, `instructors_teach_classes_class_info_id`),
  CONSTRAINT `fk_grade_info_instructors_teach_classes1`
    FOREIGN KEY (`instructors_teach_classes_instructor_info_id` , `instructors_teach_classes_class_info_id`)
    REFERENCES `mydb`.`instructors_teach_classes` (`instructor_info_id` , `class_info_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 55655;

SHOW WARNINGS;
CREATE INDEX `fk_grade_info_instructors_teach_classes1_idx` ON `mydb`.`grade_info` (`instructors_teach_classes_instructor_info_id` ASC, `instructors_teach_classes_class_info_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`department_and_instructor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`department_and_instructor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`department_and_instructor` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`instructor_gives_grade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructor_gives_grade` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`instructor_gives_grade` (
  `instructor_info_id` INT(11) UNSIGNED NOT NULL,
  `grade_info_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`instructor_info_id`, `grade_info_id`),
  CONSTRAINT `fk_instructor_info_has_grade_info_instructor_info1`
    FOREIGN KEY (`instructor_info_id`)
    REFERENCES `mydb`.`instructor_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_instructor_info_has_grade_info_grade_info1`
    FOREIGN KEY (`grade_info_id`)
    REFERENCES `mydb`.`grade_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_instructor_info_has_grade_info_grade_info1_idx` ON `mydb`.`instructor_gives_grade` (`grade_info_id` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_instructor_info_has_grade_info_instructor_info1_idx` ON `mydb`.`instructor_gives_grade` (`instructor_info_id` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`instructor_teaches_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`instructor_teaches_classes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`instructor_teaches_classes` (
)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `mydb`.`departments_and_instructors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`departments_and_instructors` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `mydb`.`departments_and_instructors` (
  `department_info_id` INT(11) UNSIGNED NOT NULL,
  `instructor_info_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`department_info_id`, `instructor_info_id`),
  CONSTRAINT `fk_department_info_has_instructor_info_department_info1`
    FOREIGN KEY (`department_info_id` , `instructor_info_id`)
    REFERENCES `mydb`.`department_info` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_department_info_has_instructor_info_instructor_info1`
    FOREIGN KEY (`instructor_info_id`)
    REFERENCES `mydb`.`instructor_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_department_info_has_instructor_info_instructor_info1_idx` ON `mydb`.`departments_and_instructors` (`instructor_info_id` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
